name: edulive
description: Plateforme de cours particuliers et répétitions en temps réel
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  provider: ^6.1.2
  flutter_webrtc: ^1.6.2+hotfix.1
  shared_preferences: ^2.3.2
  file_picker: ^12.3.0
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
